### ISSUE TITLE
Wildcard type for unknown types to avoid crashing.

### ISSUE THREAD

**Issue by Sigurdw** [eventh/kpro9#8]
We should make some kind of wildcard type to encapsulate unknown types in the lua dissector. This type should just show the member name, the name of the real type and display the hex value for this type.

This is important because we shouldn't crash/stop either our utility or wireshark if there is a single type we can not support. In batch-mode with neste structs this could be very bad.

**Comment by eventh** [comment]
We can't get the hex value (or any value) without knowing the size. If we assume size other than 0, it will create really obscure bugs if there are any other struct members following. Even size 0 would be problematic.

We could assume unknown types are signed int32 of byte size 4, but probably the best solution is to raise an Exception if we are asked to create a dissector for a member of unknown type, so that it can be noticed and fixed, or support added to our tool.

Maybe instead we should generate some validation of buffer length versus expected protocol size, and warn if protocols are used on too short buffers.

**Comment by eventh** [comment]
We have decided the best solution is to create a ProtoField.bytes() for unknown types, as long as we know the size of the type. Its about C types which there are no equal ProtoField types, instead of unknown types problem.

**Comment by eventh** [comment]
I think its been implemented in 2063efbc976a525d51c806f8317a396f855b9fac. If we know the size, but not the wireshark field type, we simply show it as bytes. I have a terrible migraine at the moment, so don't know it the solution is solid yet. Need to write some tests. Closing this.
